version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: trick_lor
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - mysql

  mysql:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: trick_lor_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password